# Project: Ace of Space
# Makefile created by Dev-C++ 4.9.9.2

CPP  = g++.exe
CC   = gcc.exe
WINDRES = windres.exe
RES  = 
OBJ  = main.o Object.o Vector.o Game.o Timer.o Texture.o Sprite.o Level.o Player.o Particle.o Enemy.o GameObject.o Asteroid.o Projectile.o Missile.o Bullet.o StraightShooter.o TargetShooter.o Fireball.o Item.o Sound.o Star.o Starfield.o Boss.o Kamikaze.o Powerup.o Miniboss.o $(RES)
LINKOBJ  = main.o Object.o Vector.o Game.o Timer.o Texture.o Sprite.o Level.o Player.o Particle.o Enemy.o GameObject.o Asteroid.o Projectile.o Missile.o Bullet.o StraightShooter.o TargetShooter.o Fireball.o Item.o Sound.o Star.o Starfield.o Boss.o Kamikaze.o Powerup.o Miniboss.o $(RES)
LIBS =  -L"C:/Program Files/Dev-Cpp/lib" -L"C:/Documents and Settings/Jason/My Documents/SDL-Mingw32/lib" -L"C:/Documents and Settings/Jason/My Documents/OpenGL/lib" -mwindows -lmingw32 -lSDLmain -lSDL -lSDL_image -lSDL_ttf -lSDL_mixer  
INCS =  -I"C:/Program Files/Dev-Cpp/include" 
CXXINCS =  -I"C:/Program Files/Dev-Cpp/lib/gcc/mingw32/3.4.2/include"  -I"C:/Program Files/Dev-Cpp/include/c++/3.4.2/backward"  -I"C:/Program Files/Dev-Cpp/include/c++/3.4.2/mingw32"  -I"C:/Program Files/Dev-Cpp/include/c++/3.4.2"  -I"C:/Program Files/Dev-Cpp/include"  -I"C:/Documents and Settings/Jason/My Documents/SDL-Mingw32/include"  -I"C:/Documents and Settings/Jason/My Documents/OpenGL/include" 
BIN  = "Ace of Space.exe"
CXXFLAGS = $(CXXINCS)  
CFLAGS = $(INCS)  
RM = rm -f

.PHONY: all all-before all-after clean clean-custom

all: all-before "Ace of Space.exe" all-after


clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o "Ace of Space.exe" $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)

Object.o: Object.cpp
	$(CPP) -c Object.cpp -o Object.o $(CXXFLAGS)

Vector.o: Vector.cpp
	$(CPP) -c Vector.cpp -o Vector.o $(CXXFLAGS)

Game.o: Game.cpp
	$(CPP) -c Game.cpp -o Game.o $(CXXFLAGS)

Timer.o: Timer.cpp
	$(CPP) -c Timer.cpp -o Timer.o $(CXXFLAGS)

Texture.o: Texture.cpp
	$(CPP) -c Texture.cpp -o Texture.o $(CXXFLAGS)

Sprite.o: Sprite.cpp
	$(CPP) -c Sprite.cpp -o Sprite.o $(CXXFLAGS)

Level.o: Level.cpp
	$(CPP) -c Level.cpp -o Level.o $(CXXFLAGS)

Player.o: Player.cpp
	$(CPP) -c Player.cpp -o Player.o $(CXXFLAGS)

Particle.o: Particle.cpp
	$(CPP) -c Particle.cpp -o Particle.o $(CXXFLAGS)

Enemy.o: Enemy.cpp
	$(CPP) -c Enemy.cpp -o Enemy.o $(CXXFLAGS)

GameObject.o: GameObject.cpp
	$(CPP) -c GameObject.cpp -o GameObject.o $(CXXFLAGS)

Asteroid.o: Asteroid.cpp
	$(CPP) -c Asteroid.cpp -o Asteroid.o $(CXXFLAGS)

Projectile.o: Projectile.cpp
	$(CPP) -c Projectile.cpp -o Projectile.o $(CXXFLAGS)

Missile.o: Missile.cpp
	$(CPP) -c Missile.cpp -o Missile.o $(CXXFLAGS)

Bullet.o: Bullet.cpp
	$(CPP) -c Bullet.cpp -o Bullet.o $(CXXFLAGS)

StraightShooter.o: StraightShooter.cpp
	$(CPP) -c StraightShooter.cpp -o StraightShooter.o $(CXXFLAGS)

TargetShooter.o: TargetShooter.cpp
	$(CPP) -c TargetShooter.cpp -o TargetShooter.o $(CXXFLAGS)

Fireball.o: Fireball.cpp
	$(CPP) -c Fireball.cpp -o Fireball.o $(CXXFLAGS)

Item.o: Item.cpp
	$(CPP) -c Item.cpp -o Item.o $(CXXFLAGS)

Sound.o: Sound.cpp
	$(CPP) -c Sound.cpp -o Sound.o $(CXXFLAGS)

Star.o: Star.cpp
	$(CPP) -c Star.cpp -o Star.o $(CXXFLAGS)

Starfield.o: Starfield.cpp
	$(CPP) -c Starfield.cpp -o Starfield.o $(CXXFLAGS)

Boss.o: Boss.cpp
	$(CPP) -c Boss.cpp -o Boss.o $(CXXFLAGS)

Kamikaze.o: Kamikaze.cpp
	$(CPP) -c Kamikaze.cpp -o Kamikaze.o $(CXXFLAGS)

Powerup.o: Powerup.cpp
	$(CPP) -c Powerup.cpp -o Powerup.o $(CXXFLAGS)

Miniboss.o: Miniboss.cpp
	$(CPP) -c Miniboss.cpp -o Miniboss.o $(CXXFLAGS)
